
FROM nginx:1.21.5-alpine

# Copy the contents of the current directory to the '/usr/share/nginx/html' directory in the container
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
